### ISSUE TITLE
ETFs supported?

### ISSUE THREAD

**Issue by taylormia** [srMarquinho/ultimate-dividend-portfolio#12]
When I add an ETF (example. JEPI) in the Transactions tab, the portfolio tab show that it isan ETF but there is no data that is populated with N/A . Am I missing something or does the spreadsheet not track EFTs?
Thanks for your help.

**Comment by srMarquinho** [comment]
@taylormia It should work with ETFs, yes. I have just tried `JEPI` and it looks like it displays the correct information for me. If this is still a problem for you, could you share more details, please?
Since this answer the question I'm closing this ticket. However, don't hesitate to continue this thread. 
Thank you.

**Comment by taylormia** [comment]
I see the name of the ETF and the Market Price but no Dividend Yield. 
![image](https://user-images.githubusercontent.com/34145387/194684725-998ea761-b32d-4390-a7e7-df8866e63a74.png)

**Comment by srMarquinho** [comment]
I see. Unfortunately, that's a piece of information that's either not found or found to be unreliable to scrape It from I'm afraid.  I suggest adding that info via the overrides section. :( I hope that helps. Thanks.
